project:
  output-dir: docs
  render:
    - bio300b_logistics.qmd
    - lecture_1_data_lifecycle.qmd
    - lecture_2_using_r.qmd
    - lecture_3_data_manipulation.qmd
    - lecture_4_data_visualisation.qmd
    - lecture_5_experimental_design.qmd
    - lecture_6_descriptive.qmd
    - lecture_7_linear_regression1.qmd
    - lecture_8_multiple_regression.qmd
    - lecture_9_generalised_linear_models.qmd
execute:
  freeze: auto



