project:
  output-dir: docs
  render:
    - bio300b_logistics.qmd
    - lecture_1_data_lifecycle.qmd
    - lecture_2_using_r.qmd
    - lecture_3_data_manipulation.qmd
    - lecture_4_data_visualisation.qmd
    - lecture_5_experimental_design.qmd
execute:
  freeze: auto



