---
title: 'Datalab 8: Generalised linear models'
date: today
format: html
---


# Part 1

Relationship between Southern Ocean diatom richness and sea surface temperature.

Data, Esper and Geronde (2014; https://doi.org/10.1016/j.palaeo.2014.08.008), give diatom assemblage composition from surface samples across the Southern Ocean. 
Column "Diatoms [#]" shows the total number of diatoms observed.
Temperature data are not given (could be extracted from an atlas with latitude/longitude), so we will use latitude as a proxy for temperature.

## Download and import data

- Download data as tab-delimited test from https://doi.pangaea.de/10.1594/PANGAEA.828674
- Import the data into R

## Process data

- Tidy the data and find the species richness for each site ("Event") (i.e. number of diatoms with a percent > 0) 

## plot and model data

- plot richness against latitude
- fit an appropriate model to find the relationship between richness and latitude
- plot the fitted values from the model with the raw data. Is the model a good fit. Do you need to add extra terms?
- interpret the model coefficients

# Part 2

Find the relationship of the presence-absence of _Fragilariopsis cylindrus_ 'F. cylindrus [%]', a sea-ice associated diatom with latitude in the data from above. 

- plot the data
- fit an appropriate model
- add the fitted model, with uncertainties, to the plot

# Part 3

Find the relationship between the relative abundance of  _Fragilariopsis kerguelensis_ ("F. kerguelensis [%]"), perhaps the most abundant diatom in the Southern Ocean, with latitude

- plot the data
- fit an appropriate model including a quadratic term if necessary
- is there evidence of overdispersion?
- adjust the model if necessary
- add the fitted model, with uncertainties, to the plot
